apiVersion: aoldacraft.com/v1alpha1
kind: MinecraftServerGroup
metadata:
  name: minecraft-server
  namespace: default
spec:
  version: "1.20.1"
  replicas: 1
  eula: true
  resourceRequirements:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "2Gi"
